# Generated by Django 6.0.5 on 2026-05-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playeranswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'session')},
        ),
    ]
