# Generated by Django 6.0.5 on 2026-05-15 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_existing_quiz_owner(apps, schema_editor):
    Quiz = apps.get_model('core', 'Quiz')
    User = apps.get_model('auth', 'User')

    owner, _ = User.objects.get_or_create(
        username='legacy_owner',
        defaults={
            'is_active': False,
            'password': '!',
        },
    )
    Quiz.objects.filter(owner__isnull=True).update(owner=owner)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_existing_quiz_owner, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
