# Generated by Django 5.2.14 on 2026-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
